# Generated by Django 5.1.6 on 2025-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1023)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.password')),
            ],
        ),
        migrations.AddField(
            model_name='password',
            name='password_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.passwordtype'),
        ),
        migrations.AddField(
            model_name='password',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.place'),
        ),
    ]
