# Generated by Django 5.1.6 on 2025-03-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_code_owner_vote_code_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='worked',
            field=models.BooleanField(),
        ),
    ]
