# Generated by Django 5.1.6 on 2025-03-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vote_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='owner',
        ),
    ]
